name: Predict
run-name: ${{ github.workflow }} (${{ github.event_name  }} - ${{ github.ref_name }})

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release_predict:
    name: Predict Next Version
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for NPM provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # pull the actual branch instead of pulling the PR virtual branch so that
          # semantic release has the right reference (otherwise will throw with invalid branch name)
          ref: ${{ (github.event_name == 'pull_request' && github.head_ref) || github.ref_name }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: npm

      - name: Install Dependencies
        run: npm i --no-save # as NPM CI cleans node_modules (faster)

      - name: Predict Next Version
        run: npm exec -- lerna version --yes  --no-git-tag-version --no-push --no-private
