name: Release

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # publish a GitHub release
      issues: write # comment on released issues
      pull-requests: write # comment on released pull requests
      id-token: write # enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install Dependencies
        run: pnpm ci

      - name: Build
        run: pnpm run build

      - name: Run Lint
        run: pnpm run lint

      - name: Run Tests
        run: pnpm run test

      - name: Setup NPM Auth
        run: |
          echo "//registry.npmjs.org :_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
          echo "access=public" >> .npmrc

      - name: Publish packages to NPM
        run: pnpm run publish


      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm exec -- semantic-release
